### ISSUE TITLE
Where are the 'cfmask' bands?

### ISSUE THREAD

**Issue by shahriar49** [bullocke/gee_pyccd#1]
There is no bands named 'cfmask' or 'cfmask_conf' in Landsat collections. What do you mean by these names in lines 140 and 143 of your code?

**Comment by myzhenghr** [comment]
> There is no bands named 'cfmask' or 'cfmask_conf' in Landsat collections. What do you mean by these names in lines 140 and 143 of your code?

Hi, shahriar49,
The band configuration of Landsat Surface Reflectance data have been updated, and the band "pixel_qa" indicate the cloud quality. You should modify bullocke's code in the main and pa program to satisfy the newest band configuration.

**Comment by shahriar49** [comment]
Thanks for reply, got it.
